# Generated by Django 4.2.4 on 2024-01-19 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Desire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire_name', models.CharField(max_length=264)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desire_app.category')),
            ],
        ),
    ]
