# Generated by Django 4.2.4 on 2024-03-03 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desire_app', '0003_alter_desire_category'),
        ('survey_app', '0003_alter_preference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='desire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='desire_app.desire'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
